# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBb293kjWnih15y1xXi3I2W2U_Q5DVG3
"""

!pip install transformers
!pip install torch torchvision
!pip install pillow

"""### Captioning"""

from transformers import BlipProcessor, BlipForConditionalGeneration
import torch
from PIL import Image
import requests

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

# آدرس یک عکس واقعی
img_url = "https://images.unsplash.com/photo-1493612276216-ee3925520721?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmFuZG9tfGVufDB8fDB8fHww"
# دریافت تصویر و تبدیلش به RGB
image = Image.open(requests.get(img_url, stream=True).raw).convert('RGB')
image

# تبدیل تصویر به ورودی مدل
inputs = processor(image, return_tensors="pt")

# اجرای مدل و تولید خروجی
out = model.generate(**inputs)

# ترجمه‌ی خروجی به متن قابل خواندن
caption = processor.decode(out[0], skip_special_tokens=True)

print("📷 کپشن تولید شده:", caption)

"""### VQA"""

from transformers import BlipForQuestionAnswering, BlipProcessor

# لود مدل و پردازنده
processor2 = BlipProcessor.from_pretrained("Salesforce/blip-vqa-base")
model2 = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base")

# لود یک تصویر
# img_url = "https://storage.googleapis.com/sfr-vision-language-research/BLIP/demo.jpg"
img_url = "https://images.unsplash.com/photo-1493612276216-ee3925520721?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmFuZG9tfGVufDB8fDB8fHww"
image = Image.open(requests.get(img_url, stream=True).raw).convert('RGB')

# سوال متنی
# question = "What is the girl doing?"
question = "What color is the dress's fabric?"
image

# آماده‌سازی ورودی
inputs = processor2(image, question, return_tensors="pt")

# تولید پاسخ
out = model2.generate(**inputs)

# دیکودینگ پاسخ
answer = processor2.decode(out[0], skip_special_tokens=True)
print("🤔 پاسخ:", answer)