# -*- coding: utf-8 -*-
"""Untitled64.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZrIxss83my21XQeMYfmfjsjZdMsTjCB
"""

!pip install diffusers transformers accelerate safetensors
!pip install gradio

import torch
from diffusers import StableDiffusionPipeline

# لود مدل (نیاز به GPU داره برای عملکرد بهتر)
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    torch_dtype=torch.float16
).to("cuda")

prompt = "a futuristic city with flying cars at sunset"
image = pipe(prompt).images[0]
image.show()

import gradio as gr

def generate_image(prompt):
    image = pipe(prompt).images[0]
    return image

gr.Interface(
    fn=generate_image,
    inputs=gr.Textbox(lines=2, placeholder="مثلاً: A cyberpunk cat with glasses"),
    outputs="image",
    title="🧠 Text to Image Generator",
    description="با وارد کردن متن، تصویر بساز!",
    theme="default"
).launch()